#!/usr/bin/env python3
# nxs-nightlight-overlay - strato traslucido "caldo" a schermo intero.
#
# Perche' non solo xrandr --gamma: su GPU VIRTUALI (VirtualBox/QEMU/VMware) la
# correzione gamma spesso NON e' supportata dal driver e viene ignorata (il
# filtro "non fa nulla"). Un overlay traslucido, composito da picom, funziona
# ovunque. La finestra e' override-redirect (POPUP), sempre in primo piano, e
# LASCIA PASSARE i click (input shape vuota): non intercetta il mouse.
#
# Sicurezza: se non riesce a rendersi trasparente ai click, si CHIUDE subito
# (meglio nessun filtro che una finestra che blocca il puntatore).
#
# Uso: nxs-nightlight-overlay [intensita' 0..0.5]   (default 0.20)
import sys

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, Gdk  # noqa: E402
import cairo  # noqa: E402

try:
    strength = float(sys.argv[1]) if len(sys.argv) > 1 else 0.20
except ValueError:
    strength = 0.20
strength = max(0.0, min(0.5, strength))

win = Gtk.Window(type=Gtk.WindowType.POPUP)     # override-redirect: niente WM
screen = win.get_screen()
vis = screen.get_rgba_visual()
if vis is not None:
    win.set_visual(vis)
win.set_app_paintable(True)
win.set_decorated(False)
win.set_keep_above(True)
win.set_accept_focus(False)
win.set_skip_taskbar_hint(True)
win.set_skip_pager_hint(True)

w = screen.get_width() or 1920
h = screen.get_height() or 1080
win.move(0, 0)
win.set_default_size(w, h)


def _draw(_widget, cr):
    # tinta ambra calda; OPERATOR_SOURCE cosi' l'alpha e' esattamente 'strength'
    cr.set_operator(cairo.OPERATOR_SOURCE)
    cr.set_source_rgba(1.0, 0.55, 0.15, strength)
    cr.paint()
    return False


win.connect("draw", _draw)


def _on_realize(_w):
    gdkwin = win.get_window()
    try:
        gdkwin.input_shape_combine_region(cairo.Region(), 0, 0)  # click passano
    except Exception:
        # non riusciamo a garantire il pass-through: NON blocchiamo il mouse
        win.destroy()
        Gtk.main_quit()
        return
    try:
        win.resize(w, h)
    except Exception:
        pass


win.connect("realize", _on_realize)
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
